<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="preload" href="/_next/static/media/569ce4b8f30dc480-s.p.woff2" as="font" crossorigin="" type="font/woff2"/>
        <link rel="preload" href="/_next/static/media/93f479601ee12b01-s.p.woff2" as="font" crossorigin="" type="font/woff2"/>
        <link rel="stylesheet" href="style.css" data-precedence="next"/>
        <link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/webpack-29ebadaebe2fcb3f.js"/>
        <script src="/_next/static/chunks/4bd1b696-f6a08746561b241a.js" async=""></script>
        <script src="/_next/static/chunks/517-b70844aa2bc05871.js" async=""></script>
        <script src="/_next/static/chunks/main-app-a849309caff0f7ba.js" async=""></script>
        <script src="/_next/static/chunks/565-fce66d4e89fe5ab9.js" async=""></script>
        <script src="/_next/static/chunks/173-f7e00043398e9d1e.js" async=""></script>
        <script src="/_next/static/chunks/706-3aaec32b420c99ff.js" async=""></script>
        <script src="/_next/static/chunks/app/admin/page-5c4062d7a7b651ee.js" async=""></script>
        <meta name="next-size-adjust" content=""/>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16"/>
        <script src="/_next/static/chunks/polyfills-42372ed130431b0a.js" noModule=""></script>
    </head>
    <body class="__variable_4d318d __variable_ea5f4b antialiased">
        <div class="flex w-full min-h-screen text-text font-Urbanist overflow-hidden">
            <aside class="w-[80px] h-full bg-white border-r border-blue_Gray flex flex-col py-4">
                <div class="mb-40 flex justify-center pt-6">
                    <img alt="Private Docs Logo" loading="lazy" width="34" height="37" decoding="async" data-nimg="1" class="w-[163px] h-[36px]" style="color:transparent" src="/_next/static/media/Logo Private.4734f4a1.svg"/>
                </div>
                <nav class="flex flex-col space-y-2 w-full flex-1">
                    <a class="flex justify-center items-center w-full py-4 text-light_text" href="/dashboard">
                        <svg class="text-inherit w-6 h-6" width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9.02 3.33999L3.63 7.53999C2.73 8.23999 2 9.72999 2 10.86V18.27C2 20.59 3.89 22.49 6.21 22.49H17.79C20.11 22.49 22 20.59 22 18.28V11C22 9.78999 21.19 8.23999 20.2 7.54999L14.02 3.21999C12.62 2.23999 10.37 2.28999 9.02 3.33999Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M12 18.49V15.49" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                    <a class="flex justify-center items-center w-full py-4 text-light_text" href="/organisations">
                        <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" class="text-inherit w-6 h-6">
                            <path d="M17.3333 29.3333H6.66663C3.99996 29.3333 2.66663 28 2.66663 25.3333V14.6667C2.66663 12 3.99996 10.6667 6.66663 10.6667H13.3333V25.3333C13.3333 28 14.6666 29.3333 17.3333 29.3333Z" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M13.4799 5.33333C13.3733 5.73333 13.3333 6.17333 13.3333 6.66666V10.6667H6.66663V7.99999C6.66663 6.53333 7.86663 5.33333 9.33329 5.33333H13.4799Z" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M18.6666 10.6667V17.3333" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M24 10.6667V17.3333" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M22.6666 22.6667H20C19.2666 22.6667 18.6666 23.2667 18.6666 24V29.3333H24V24C24 23.2667 23.4 22.6667 22.6666 22.6667Z" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M8 17.3333V22.6667" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M13.3334 25.3333V6.66667C13.3334 4.00001 14.6667 2.66667 17.3334 2.66667H25.3334C28 2.66667 29.3334 4.00001 29.3334 6.66667V25.3333C29.3334 28 28 29.3333 25.3334 29.3333H17.3334C14.6667 29.3333 13.3334 28 13.3334 25.3333Z" stroke="currentColor" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                    <a class="flex justify-center items-center w-full py-4 border-r-4 border-primary text-primary" href="/admin">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
                            <path d="M9.16006 10.87C9.06006 10.86 8.94006 10.86 8.83006 10.87C6.45006 10.79 4.56006 8.84 4.56006 6.44C4.56006 3.99 6.54006 2 9.00006 2C11.4501 2 13.4401 3.99 13.4401 6.44C13.4301 8.84 11.5401 10.79 9.16006 10.87Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M16.41 4C18.35 4 19.91 5.57 19.91 7.5C19.91 9.39 18.41 10.93 16.54 11C16.46 10.99 16.37 10.99 16.28 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M4.15997 14.56C1.73997 16.18 1.73997 18.82 4.15997 20.43C6.90997 22.27 11.42 22.27 14.17 20.43C16.59 18.81 16.59 16.17 14.17 14.56C11.43 12.73 6.91997 12.73 4.15997 14.56Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M18.3401 20C19.0601 19.85 19.7401 19.56 20.3001 19.13C21.8601 17.96 21.8601 16.03 20.3001 14.86C19.7501 14.44 19.0801 14.16 18.3701 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                </nav>
                <div class=" mt-36 ">
                    <a class="flex justify-center items-center w-full py-4 text-light_text" href="/logout">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
                            <path d="M8.8999 7.55999C9.2099 3.95999 11.0599 2.48999 15.1099 2.48999H15.2399C19.7099 2.48999 21.4999 4.27999 21.4999 8.06999V15.93C21.4999 19.72 19.7099 21.51 15.2399 21.51C11.0599 21.51 9.2099 20.04 8.8999 16.44" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M15.24 15.93H3.79999" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M5.44006 12.93L3.80006 15.03L5.44006 17.03" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                </div>
            </aside>
            <main class="flex-1 ml-5 p-8 overflow-auto">
                <header class="flex justify-between items-center mb-8">
                    <h1 class="w-[250px] h-[32px] font-Urbanist text-text text-[30px]  leading-[32px] tracking-[-0.25px] font-medium">Bienvenue, Ken B.</h1>
                    <div class="relative flex gap-x-2">
                        <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class=" border rounded-xl h-10 w-10 p-1 border-bg_2  " style="color:transparent" src="/_next/static/media/Notification Icon.543fe595.svg"/>
                        <img alt="User profile" loading="lazy" width="70" height="70" decoding="async" data-nimg="1" class="rounded-full cursor-pointer -mt-4" style="color:transparent" src="/_next/static/media/Avatar.bd86f186.svg"/>
                        <img alt="item5" loading="lazy" width="14" height="8" decoding="async" data-nimg="1" class="w-[16px] h-[16] mt-3 cursor-pointer" style="color:transparent" src="/_next/static/media/Vector.b6b2206a.svg"/>
                    </div>
                </header>
                <div class="   mt-10">
                    <div class="w-full h-[400]  pt-8 ">
                        <div class=" flex  h-12 px-4 ">
                            <div class=" gap-4 flex  h-12 ">
                                <div class=" flex   ">
                                    <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-1 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                    <div class="  items-center flex ml-4 justify-between  py-4 px-3  bg-gray rounded-3xl  w-[200px] h-[18px] ">
                                        <span class="font-urbanist text-[14px] text-light_text font-semibold leading-[20px]">Sélectionner une action</span>
                                        <img alt="che" loading="lazy" width="10" height="6" decoding="async" data-nimg="1" class="" style="color:transparent" src="/_next/static/media/Path.ffc00e44.svg"/>
                                    </div>
                                    <button class="text-center ml-96 justify-center items-center px-1 flex bg-primary rounded-3xl w-[200px] h-[40px]">
                                        <span class="font-urbanist text-center text-[14px] text-white font-semibold leading-[20px]">Ajouter un admin</span>
                                    </button>
                                </div>
                                <div class=" flex items-center bg-white border border-gray h-[40px] rounded-full px-2  shadow-sm  ">
                                    <img alt="seach" loading="lazy" width="18" height="18" decoding="async" data-nimg="1" class=" " style="color:transparent" src="/_next/static/media/Search.2ecdb860.svg"/>
                                    <input type="text" placeholder="    Rechercher une organisation                 " class=" w-[320px]   font-Urbanist text-[12px] font-normal leading-[19.2px]  focus:outline-none "/>
                                    <img alt="seeting" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class=" " style="color:transparent" src="/_next/static/media/setting-3.3a2f1002.svg"/>
                                </div>
                            </div>
                        </div>
                        <hr class="mt-8 border-2 border-gray"/>
                        <div class=" mt-10 rounded-xl bg-gray  ">
                            <table class="min-w-full">
                                <thead class=" border-gray rounded-t ">
                                    <tr class="font-Urbanist text-sm text-left font-bold leading-6 ">
                                        <th class="py-3 text-left  "></th>
                                        <th class="py-3 text-left  ">Administrateurs</th>
                                        <th class="py-2 ">Adresse e-mail</th>
                                        <th class="py-2  ">Statut</th>
                                        <th class="py-2  "></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-succes_light text-sucess
                            ">Actif</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-danger_light text-danger
                            ">Bloqué</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-succes_light text-sucess
                            ">Actif</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-danger_light text-danger
                            ">Bloqué</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-succes_light text-sucess
                            ">Actif</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-danger_light text-danger
                            ">Bloqué</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-succes_light text-sucess
                            ">Actif</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-danger_light text-danger
                            ">Bloqué</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-succes_light text-sucess
                            ">Actif</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-danger_light text-danger
                            ">Bloqué</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-succes_light text-sucess
                            ">Actif</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="border-b-2 border-dotted bg-white border-gray">
                                        <td>
                                            <img alt="case" loading="lazy" width="20" height="20" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/Rectangle.aea46228.svg"/>
                                        </td>
                                        <td class="py-3  flex items-center">
                                            <div class="flex items-center">
                                                <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue_Gray ">
                                                    <span class="font-bold font-urbanist text-primary">BE</span>
                                                </div>
                                                <span class="ml-2 font-urbanist text-[16px] font-medium leading-5">Benjamin  
                                                <!-- -->
                                                <!-- -->
                                                Evident</span>
                                            </div>
                                        </td>
                                        <td class="py-3 font-urbanist text-[16px] font-medium leading-5 ">norman@example.com</td>
                                        <td class="py-3">
                                            <span class="px-4 py-1 font-Urbanist text-sm font-medium leading-4 rounded-full text-center inline-block w-[100px]
                            bg-danger_light text-danger
                            ">Bloqué</span>
                                        </td>
                                        <td class="py-3 items-end justify-end px-4 flex space-x-2 ">
                                            <button>
                                                <img alt="item5" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="w-[24px] mt-2 h-[24px]" style="color:transparent" src="/_next/static/media/edit-2.7d8ad241.svg"/>
                                            </button>
                                            <button>
                                                <img alt="Supprimer" loading="lazy" width="24" height="24" decoding="async" data-nimg="1" class="mt-2" style="color:transparent" src="/_next/static/media/trash.3b16cabb.svg"/>
                                            </button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="flex space-x-2 mt-6 justify-end">
                            <button class="w-[38px] h-[38px] flex items-center justify-center text-light_text" disabled="">
                                <img alt="précédent" loading="lazy" width="7" height="12" decoding="async" data-nimg="1" style="color:transparent" src="/_next/static/media/chevron_left.5ef4792f.svg"/>
                            </button>
                            <button class="w-[38px] h-[38px] flex items-center justify-center bg-blue_Gray text-primary rounded-lg">1</button>
                            <button class="w-[38px] h-[38px] flex items-center justify-center text-light_text">2</button>
                            <button class="w-[38px] h-[38px] flex items-center justify-center text-light_text">3</button>
                            <button class="w-[38px] h-[38px] flex items-center justify-center text-light_text">4</button>
                            <button class="w-[38px] h-[38px] flex items-center justify-center text-light_text">5</button>
                            <button class="w-[38px] h-[38px] flex items-center justify-center text-light_text">
                                <img alt="suivant" loading="lazy" width="7" height="12" decoding="async" data-nimg="1" style="color:transparent" src="/_next/static/media/chevron-right.99de8ec7.svg"/>
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <script src="/_next/static/chunks/webpack-29ebadaebe2fcb3f.js" async=""></script>
        <script>
            (self.__next_f = self.__next_f || []).push([0])
        </script>
        <script>
            self.__next_f.push([1, "1:\"$Sreact.fragment\"\n2:I[5244,[],\"\"]\n3:I[3866,[],\"\"]\n4:I[7033,[],\"ClientPageRoot\"]\n5:I[243,[\"565\",\"static/chunks/565-fce66d4e89fe5ab9.js\",\"173\",\"static/chunks/173-f7e00043398e9d1e.js\",\"706\",\"static/chunks/706-3aaec32b420c99ff.js\",\"698\",\"static/chunks/app/admin/page-5c4062d7a7b651ee.js\"],\"default\"]\n8:I[6213,[],\"OutletBoundary\"]\na:I[6213,[],\"MetadataBoundary\"]\nc:I[6213,[],\"ViewportBoundary\"]\ne:I[4835,[],\"\"]\n:HL[\"/_next/static/media/569ce4b8f30dc480-s.p.woff2\",\"font\",{\"crossOrigin\":\"\",\"type\":\"font/woff2\"}]\n:HL[\"/_next/static/media/93f479601ee12b01-s.p.woff2\",\"font\",{\"crossOrigin\":\"\",\"type\":\"font/woff2\"}]\n:HL[\"/_next/static/css/754586bcdc3f93ba.css\",\"style\"]\n"])
        </script>
        <script>
            self.__next_f.push([1, "0:{\"P\":null,\"b\":\"xJxwR76NB72RbOOtlSQ0t\",\"p\":\"\",\"c\":[\"\",\"admin\"],\"i\":false,\"f\":[[[\"\",{\"children\":[\"admin\",{\"children\":[\"__PAGE__\",{}]}]},\"$undefined\",\"$undefined\",true],[\"\",[\"$\",\"$1\",\"c\",{\"children\":[[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/754586bcdc3f93ba.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\",\"nonce\":\"$undefined\"}]],[\"$\",\"html\",null,{\"lang\":\"en\",\"children\":[\"$\",\"body\",null,{\"className\":\"__variable_4d318d __variable_ea5f4b antialiased\",\"children\":[\"$\",\"$L2\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$L3\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":[[],[[\"$\",\"title\",null,{\"children\":\"404: This page could not be found.\"}],[\"$\",\"div\",null,{\"style\":{\"fontFamily\":\"system-ui,\\\"Segoe UI\\\",Roboto,Helvetica,Arial,sans-serif,\\\"Apple Color Emoji\\\",\\\"Segoe UI Emoji\\\"\",\"height\":\"100vh\",\"textAlign\":\"center\",\"display\":\"flex\",\"flexDirection\":\"column\",\"alignItems\":\"center\",\"justifyContent\":\"center\"},\"children\":[\"$\",\"div\",null,{\"children\":[[\"$\",\"style\",null,{\"dangerouslySetInnerHTML\":{\"__html\":\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\"}}],[\"$\",\"h1\",null,{\"className\":\"next-error-h1\",\"style\":{\"display\":\"inline-block\",\"margin\":\"0 20px 0 0\",\"padding\":\"0 23px 0 0\",\"fontSize\":24,\"fontWeight\":500,\"verticalAlign\":\"top\",\"lineHeight\":\"49px\"},\"children\":404}],[\"$\",\"div\",null,{\"style\":{\"display\":\"inline-block\"},\"children\":[\"$\",\"h2\",null,{\"style\":{\"fontSize\":14,\"fontWeight\":400,\"lineHeight\":\"49px\",\"margin\":0},\"children\":\"This page could not be found.\"}]}]]}]}]]],\"forbidden\":\"$undefined\",\"unauthorized\":\"$undefined\"}]}]}]]}],{\"children\":[\"admin\",[\"$\",\"$1\",\"c\",{\"children\":[null,[\"$\",\"$L2\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\",\"admin\",\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$L3\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":\"$undefined\",\"forbidden\":\"$undefined\",\"unauthorized\":\"$undefined\"}]]}],{\"children\":[\"__PAGE__\",[\"$\",\"$1\",\"c\",{\"children\":[[\"$\",\"$L4\",null,{\"Component\":\"$5\",\"searchParams\":{},\"params\":{},\"promises\":[\"$@6\",\"$@7\"]}],null,[\"$\",\"$L8\",null,{\"children\":\"$L9\"}]]}],{},null,false]},null,false]},null,false],[\"$\",\"$1\",\"h\",{\"children\":[null,[\"$\",\"$1\",\"w3tzXYsluBinAtmkh58qq\",{\"children\":[[\"$\",\"$La\",null,{\"children\":\"$Lb\"}],[\"$\",\"$Lc\",null,{\"children\":\"$Ld\"}],[\"$\",\"meta\",null,{\"name\":\"next-size-adjust\",\"content\":\"\"}]]}]]}],false]],\"m\":\"$undefined\",\"G\":[\"$e\",\"$undefined\"],\"s\":false,\"S\":true}\n"])
        </script>
        <script>
            self.__next_f.push([1, "6:{}\n7:{}\n"])
        </script>
        <script>
            self.__next_f.push([1, "d:[[\"$\",\"meta\",\"0\",{\"name\":\"viewport\",\"content\":\"width=device-width, initial-scale=1\"}]]\nb:[[\"$\",\"meta\",\"0\",{\"charSet\":\"utf-8\"}],[\"$\",\"title\",\"1\",{\"children\":\"Create Next App\"}],[\"$\",\"meta\",\"2\",{\"name\":\"description\",\"content\":\"Generated by create next app\"}],[\"$\",\"link\",\"3\",{\"rel\":\"icon\",\"href\":\"/favicon.ico\",\"type\":\"image/x-icon\",\"sizes\":\"16x16\"}]]\n"])
        </script>
        <script>
            self.__next_f.push([1, "9:null\n"])
        </script>
    </body>
</html>
